#!/bin/zsh

if ! command -v pandoc &>/dev/null; then
  echo "pandoc is not installed"
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Installing pandoc via Homebrew"
    brew install pandoc

  elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if [[ $(lsb_release -is) == "Arch" && $(whoami) == "dakota" ]]; then
      echo "Installing pandoc via pacman"
      if command -v paru &>/dev/null; then
        echo "Installing pandoc via paru"
        paru -S pandoc
      elif command -v yay &>/dev/null; then
        echo "Installing pandoc via yay"
        yay -S pandoc
      else
        echo "Please install pandoc"
        exit 1
      fi
    elif [[ $(lsb_release -is) == "ubuntu" ]]; then
      echo "Installing pandoc via apt"
      sudo apt install pandoc
    else
      echo "Please install pandoc"
      exit 1
    fi
  fi
else
  for file in *.htm; do
    base_name=$(basename $file .htm)
    mv "$file" "$base_name.pdf"
    # pandoc "$file" -o "$base_name.pdf"
  done
fi

# vim: ft=sh ts=2 sw=2 et
