#!/bin/zsh

ghsrc ()
{
  # Capture the output of gh s $1
  repo_url=$(gh s $1 | awk '{print $NF}')

  # Check if the output is not empty
  if [ -n "$repo_url" ]; then
    # Clone the repository using gh repo clone
    gh repo clone "$repo_url"
  else
    echo "No repository found for the query: $1"
  fi
}
