#!/bin/zsh

set -e

force=false
[[ "$1" == "--force" || "$1" == "-f" ]] && force=true

pushd $(pwd)

if [[ $(uname) == "Darwin" ]]; then
  if ! command -v brew &>/dev/null; then
    echo "brew is not installed"
    exit 1
  elif ! command -v nvim &>/dev/null; then
    echo "neovim is not installed!"
    #echo "installing neovim..."
    #brew install --cask wezterm@nightly
    exit 1
  else
    # brew upgrade neovim --HEAD
    if [[ -d ${XDG_PROJECTS_DIR}/neovim ]]; then
      pushd ${XDG_PROJECTS_DIR}/neovim
      git fetch
      local has_changes=$(git rev-list HEAD...origin/master --count)
      if [[ $force == true ]] || [[ $has_changes != 0 ]]; then
        [[ $force == true ]] && echo "Forcing rebuild..."
        if [[ -d build ]]; then
          git reset --hard && git clean --force -dfx && git pull
        fi
        if command -v make &>/dev/null; then
          local nprocs=$(($(sysctl -n hw.logicalcpu) - 1))
          make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$HOME/.local \
            CC=clang CXX=clang++ \
            CFLAGS="-O3 -mcpu=apple-m4 -ffast-math -flto=full -fstack-protector-strong -fno-plt" \
            LDFLAGS="-flto=full" \
            -j$nprocs
          make install
        else
          echo "make is not installed"
          exit 1
        fi
      fi
      popd
    fi
  fi
elif [[ $(lsb_release -is) == "Arch" && $(whoami) == "dakota" ]]; then
  if ! command -v nvim &>/dev/null; then
    echo "neovim is not installed!"
  else
    if [[ -d ${XDG_PROJECTS_DIR}/neovim ]]; then
      pushd ${XDG_PROJECTS_DIR}/neovim
      git fetch
      local has_changes=$(git rev-list HEAD...origin/master --count)
      if [[ $force == true ]] || [[ $has_changes != 0 ]]; then
        [[ $force == true ]] && echo "Forcing rebuild..."
        if [[ -d build ]]; then
          git reset --hard && git clean --force -dfx && git pull
        fi
        if command -v make &>/dev/null; then
          make CC=clang CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$HOME/.local CFLAGS="-march=znver5 \
            -mtune=znver5 -Ofast -lm -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
            -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
          make install
        else
          echo "make is not installed"
          exit 1
        fi
      fi
      popd
    fi
  fi
fi

popd

# vim: set ft=sh ts=2 sw=2 et:
